// Gallery data with corrected 64 images - realistic distribution
const galleryData = [
    { src: 'images/gallery-optimized/gallery_001.jpg', thumb: 'images/thumbs/gallery_001_thumb.jpg', location: 'espalda', title: 'Espalda Tribal 1', description: 'Pieza central' },
    { src: 'images/gallery-optimized/gallery_002.jpg', thumb: 'images/thumbs/gallery_002_thumb.jpg', location: 'espalda', title: 'Espalda Superior 2', description: 'Masterpiece' },
    { src: 'images/gallery-optimized/gallery_003.jpg', thumb: 'images/thumbs/gallery_003_thumb.jpg', location: 'pierna', title: 'Pantorrilla Arte 3', description: 'Arte personalizado' },
    { src: 'images/gallery-optimized/gallery_004.jpg', thumb: 'images/thumbs/gallery_004_thumb.jpg', location: 'brazo', title: 'Brazo Dotwork 4', description: 'Líneas precisas' },
    { src: 'images/gallery-optimized/gallery_005.jpg', thumb: 'images/thumbs/gallery_005_thumb.jpg', location: 'pierna', title: 'Arte en Pierna 5', description: 'Composición fluida' },
    { src: 'images/gallery-optimized/gallery_006.jpg', thumb: 'images/thumbs/gallery_006_thumb.jpg', location: 'brazo', title: 'Brazo Blackwork 6', description: 'Diseño único' },
    { src: 'images/gallery-optimized/gallery_007.jpg', thumb: 'images/thumbs/gallery_007_thumb.jpg', location: 'brazo', title: 'Brazo Dotwork 7', description: 'Diseño único' },
    { src: 'images/gallery-optimized/gallery_008.jpg', thumb: 'images/thumbs/gallery_008_thumb.jpg', location: 'brazo', title: 'Brazo Dotwork 8', description: 'Líneas precisas' },
    { src: 'images/gallery-optimized/gallery_009.jpg', thumb: 'images/thumbs/gallery_009_thumb.jpg', location: 'espalda', title: 'Espalda Completa 9', description: 'Trabajo extenso' },
    { src: 'images/gallery-optimized/gallery_010.jpg', thumb: 'images/thumbs/gallery_010_thumb.jpg', location: 'espalda', title: 'Obra Maestra 10', description: 'Obra de gran formato' },
    { src: 'images/gallery-optimized/gallery_011.jpg', thumb: 'images/thumbs/gallery_011_thumb.jpg', location: 'brazo', title: 'Manga Completa 11', description: 'Composición armónica' },
    { src: 'images/gallery-optimized/gallery_012.jpg', thumb: 'images/thumbs/gallery_012_thumb.jpg', location: 'brazo', title: 'Brazo Tribal 12', description: 'Estilo contemporáneo' },
    { src: 'images/gallery-optimized/gallery_013.jpg', thumb: 'images/thumbs/gallery_013_thumb.jpg', location: 'brazo', title: 'Manga Completa 13', description: 'Composición armónica' },
    { src: 'images/gallery-optimized/gallery_014.jpg', thumb: 'images/thumbs/gallery_014_thumb.jpg', location: 'pierna', title: 'Pantorrilla Arte 14', description: 'Estilo único' },
    { src: 'images/gallery-optimized/gallery_015.jpg', thumb: 'images/thumbs/gallery_015_thumb.jpg', location: 'brazo', title: 'Tatuaje Lineal 15', description: 'Composición armónica' },
    { src: 'images/gallery-optimized/gallery_016.jpg', thumb: 'images/thumbs/gallery_016_thumb.jpg', location: 'brazo', title: 'Diseño de Brazo 16', description: 'Arte geométrico fluido' },
    { src: 'images/gallery-optimized/gallery_017.jpg', thumb: 'images/thumbs/gallery_017_thumb.jpg', location: 'brazo', title: 'Diseño de Brazo 17', description: 'Arte geométrico fluido' },
    { src: 'images/gallery-optimized/gallery_018.jpg', thumb: 'images/thumbs/gallery_018_thumb.jpg', location: 'espalda', title: 'Arte Dorsal 18', description: 'Obra de gran formato' },
    { src: 'images/gallery-optimized/gallery_019.jpg', thumb: 'images/thumbs/gallery_019_thumb.jpg', location: 'espalda', title: 'Espalda Tribal 19', description: 'Trabajo extenso' },
    { src: 'images/gallery-optimized/gallery_020.jpg', thumb: 'images/thumbs/gallery_020_thumb.jpg', location: 'brazo', title: 'Antebrazo Geométrico 20', description: 'Líneas precisas' },
    { src: 'images/gallery-optimized/gallery_021.jpg', thumb: 'images/thumbs/gallery_021_thumb.jpg', location: 'brazo', title: 'Brazo Tribal 21', description: 'Estilo contemporáneo' },
    { src: 'images/gallery-optimized/gallery_022.jpg', thumb: 'images/thumbs/gallery_022_thumb.jpg', location: 'brazo', title: 'Brazo Blackwork 22', description: 'Composición armónica' },
    { src: 'images/gallery-optimized/gallery_023.jpg', thumb: 'images/thumbs/gallery_023_thumb.jpg', location: 'pierna', title: 'Muslo Completo 23', description: 'Diseño orgánico' },
    { src: 'images/gallery-optimized/gallery_024.jpg', thumb: 'images/thumbs/gallery_024_thumb.jpg', location: 'brazo', title: 'Brazo Tribal 24', description: 'Estilo contemporáneo' },
    { src: 'images/gallery-optimized/gallery_025.jpg', thumb: 'images/thumbs/gallery_025_thumb.jpg', location: 'espalda', title: 'Espalda Completa 25', description: 'Arte ambicioso' },
    { src: 'images/gallery-optimized/gallery_026.jpg', thumb: 'images/thumbs/gallery_026_thumb.jpg', location: 'brazo', title: 'Brazo Ornamental 26', description: 'Composición equilibrada' },
    { src: 'images/gallery-optimized/gallery_027.jpg', thumb: 'images/thumbs/gallery_027_thumb.jpg', location: 'espalda', title: 'Espalda Superior 27', description: 'Trabajo extenso' },
    { src: 'images/gallery-optimized/gallery_028.jpg', thumb: 'images/thumbs/gallery_028_thumb.jpg', location: 'brazo', title: 'Diseño Minimalista 28', description: 'Arte moderno' },
    { src: 'images/gallery-optimized/gallery_029.jpg', thumb: 'images/thumbs/gallery_029_thumb.jpg', location: 'pierna', title: 'Muslo Completo 29', description: 'Trabajo en pierna' },
    { src: 'images/gallery-optimized/gallery_030.jpg', thumb: 'images/thumbs/gallery_030_thumb.jpg', location: 'espalda', title: 'Diseño Central 30', description: 'Arte monumental' },
    { src: 'images/gallery-optimized/gallery_031.jpg', thumb: 'images/thumbs/gallery_031_thumb.jpg', location: 'espalda', title: 'Espalda Tribal 31', description: 'Composición épica' },
    { src: 'images/gallery-optimized/gallery_032.jpg', thumb: 'images/thumbs/gallery_032_thumb.jpg', location: 'pierna', title: 'Pierna Floral 32', description: 'Arte adaptado a anatomía' },
    { src: 'images/gallery-optimized/gallery_033.jpg', thumb: 'images/thumbs/gallery_033_thumb.jpg', location: 'pierna', title: 'Diseño de Muslo 33', description: 'Estilo único' },
    { src: 'images/gallery-optimized/gallery_034.jpg', thumb: 'images/thumbs/gallery_034_thumb.jpg', location: 'espalda', title: 'Arte Dorsal 34', description: 'Composición épica' },
    { src: 'images/gallery-optimized/gallery_035.jpg', thumb: 'images/thumbs/gallery_035_thumb.jpg', location: 'pierna', title: 'Diseño de Muslo 35', description: 'Arte adaptado a anatomía' },
    { src: 'images/gallery-optimized/gallery_036.jpg', thumb: 'images/thumbs/gallery_036_thumb.jpg', location: 'pierna', title: 'Diseño de Muslo 36', description: 'Diseño vertical elegante' },
    { src: 'images/gallery-optimized/gallery_037.jpg', thumb: 'images/thumbs/gallery_037_thumb.jpg', location: 'pierna', title: 'Diseño de Muslo 37', description: 'Diseño orgánico' },
    { src: 'images/gallery-optimized/gallery_038.jpg', thumb: 'images/thumbs/gallery_038_thumb.jpg', location: 'brazo', title: 'Tatuaje Lineal 38', description: 'Trabajo detallado' },
    { src: 'images/gallery-optimized/gallery_039.jpg', thumb: 'images/thumbs/gallery_039_thumb.jpg', location: 'pierna', title: 'Pierna Floral 39', description: 'Diseño orgánico' },
    { src: 'images/gallery-optimized/gallery_040.jpg', thumb: 'images/thumbs/gallery_040_thumb.jpg', location: 'pierna', title: 'Diseño de Muslo 40', description: 'Diseño orgánico' },
    { src: 'images/gallery-optimized/gallery_041.jpg', thumb: 'images/thumbs/gallery_041_thumb.jpg', location: 'espalda', title: 'Obra Maestra 41', description: 'Diseño complejo' },
    { src: 'images/gallery-optimized/gallery_042.jpg', thumb: 'images/thumbs/gallery_042_thumb.jpg', location: 'brazo', title: 'Diseño Minimalista 42', description: 'Composición equilibrada' },
    { src: 'images/gallery-optimized/gallery_043.jpg', thumb: 'images/thumbs/gallery_043_thumb.jpg', location: 'pierna', title: 'Diseño de Muslo 43', description: 'Trabajo en pierna' },
    { src: 'images/gallery-optimized/gallery_044.jpg', thumb: 'images/thumbs/gallery_044_thumb.jpg', location: 'brazo', title: 'Antebrazo Geométrico 44', description: 'Composición equilibrada' },
    { src: 'images/gallery-optimized/gallery_045.jpg', thumb: 'images/thumbs/gallery_045_thumb.jpg', location: 'espalda', title: 'Gran Formato 45', description: 'Arte ambicioso' },
    { src: 'images/gallery-optimized/gallery_046.jpg', thumb: 'images/thumbs/gallery_046_thumb.jpg', location: 'espalda', title: 'Espalda Superior 46', description: 'Obra de gran formato' },
    { src: 'images/gallery-optimized/gallery_047.jpg', thumb: 'images/thumbs/gallery_047_thumb.jpg', location: 'brazo', title: 'Arte en Brazo 47', description: 'Arte geométrico fluido' },
    { src: 'images/gallery-optimized/gallery_048.jpg', thumb: 'images/thumbs/gallery_048_thumb.jpg', location: 'brazo', title: 'Manga Completa 48', description: 'Arte moderno' },
    { src: 'images/gallery-optimized/gallery_049.jpg', thumb: 'images/thumbs/gallery_049_thumb.jpg', location: 'brazo', title: 'Manga Completa 49', description: 'Diseño intrincado en brazo' },
    { src: 'images/gallery-optimized/gallery_050.jpg', thumb: 'images/thumbs/gallery_050_thumb.jpg', location: 'brazo', title: 'Brazo Tribal 50', description: 'Arte moderno' },
    { src: 'images/gallery-optimized/gallery_051.jpg', thumb: 'images/thumbs/gallery_051_thumb.jpg', location: 'espalda', title: 'Espalda Completa 51', description: 'Trabajo extenso' },
    { src: 'images/gallery-optimized/gallery_052.jpg', thumb: 'images/thumbs/gallery_052_thumb.jpg', location: 'pierna', title: 'Muslo Completo 52', description: 'Trabajo en pierna' },
    { src: 'images/gallery-optimized/gallery_053.jpg', thumb: 'images/thumbs/gallery_053_thumb.jpg', location: 'brazo', title: 'Brazo Blackwork 53', description: 'Composición armónica' },
    { src: 'images/gallery-optimized/gallery_054.jpg', thumb: 'images/thumbs/gallery_054_thumb.jpg', location: 'brazo', title: 'Brazo Blackwork 54', description: 'Arte personalizado' },
    { src: 'images/gallery-optimized/gallery_055.jpg', thumb: 'images/thumbs/gallery_055_thumb.jpg', location: 'espalda', title: 'Obra Maestra 55', description: 'Pieza central' },
    { src: 'images/gallery-optimized/gallery_056.jpg', thumb: 'images/thumbs/gallery_056_thumb.jpg', location: 'brazo', title: 'Brazo Blackwork 56', description: 'Composición armónica' },
    { src: 'images/gallery-optimized/gallery_057.jpg', thumb: 'images/thumbs/gallery_057_thumb.jpg', location: 'espalda', title: 'Obra Maestra 57', description: 'Masterpiece' },
    { src: 'images/gallery-optimized/gallery_058.jpg', thumb: 'images/thumbs/gallery_058_thumb.jpg', location: 'pierna', title: 'Arte Vertical 58', description: 'Composición fluida' },
    { src: 'images/gallery-optimized/gallery_059.jpg', thumb: 'images/thumbs/gallery_059_thumb.jpg', location: 'brazo', title: 'Manga Completa 59', description: 'Estilo contemporáneo' },
    { src: 'images/gallery-optimized/gallery_060.jpg', thumb: 'images/thumbs/gallery_060_thumb.jpg', location: 'brazo', title: 'Antebrazo Geométrico 60', description: 'Diseño único' },
    { src: 'images/gallery-optimized/gallery_061.jpg', thumb: 'images/thumbs/gallery_061_thumb.jpg', location: 'pierna', title: 'Arte en Pierna 61', description: 'Diseño vertical elegante' },
    { src: 'images/gallery-optimized/gallery_062.jpg', thumb: 'images/thumbs/gallery_062_thumb.jpg', location: 'pierna', title: 'Arte Vertical 62', description: 'Estilo único' },
    { src: 'images/gallery-optimized/gallery_063.jpg', thumb: 'images/thumbs/gallery_063_thumb.jpg', location: 'brazo', title: 'Tatuaje Lineal 63', description: 'Diseño intrincado en brazo' },
    { src: 'images/gallery-optimized/gallery_064.jpg', thumb: 'images/thumbs/gallery_064_thumb.jpg', location: 'brazo', title: 'Brazo Dotwork 64', description: 'Estilo contemporáneo' },
];
